"""empty message

Revision ID: 951a7534b238
Revises: a06199026dc4
Create Date: 2021-02-06 22:50:27.519389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951a7534b238'
down_revision = 'a06199026dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_too')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_too',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_too_pkey'),
    sa.UniqueConstraint('email', name='user_too_email_key')
    )
    # ### end Alembic commands ###
